#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Create web content

mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm
	add_header X-Served-By \$(hostname);

	location /redirect_me {
		return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}
EOF

# Restart Nginx
systemctl restart nginx
