#!/usr/bin/env bash
# Install HAproxy
apt-get update
apt-get install -y haproxy

# Configure HAproxy management via init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAproxy for load balancing
cat /etc/haproxy/haproxy.cfg << EOF
global
    log 127.0.0.1 local0 notice
    maxconn 3000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  redispatch
    retries 3
    timeout connect 5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    optionforwardfor
    server 105931-web-01 54.157.155.82 check
    server 105931-web-02 18.233.65.7 check
EOF

# HAproxy managed via init script
systemctl enable haproxy.service
systemctl start haproxy.service

