#!/usr/bin/env bash
# Install HAproxy
apt-get update
apt-get install -y haproxy=1.8.\*

# Configure HAproxy for load balancing
echo '
frontend justmogen.tech
	bind 0:80
	mode http
	default_backend web_servers

backend web_servers
	balance roundrobin
	server 105931-web-01 54.157.155.82 check
	server 105931-web-02 18.233.65.7 check
' >> /etc/haproxy/haproxy.cfg

# HAproxy managed via init script
service haproxy restart
