#!/usr/bin/env bash
# Configure dfault nginx conf file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to default conf file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
