#!/usr/bin/env bash
#  Bash script that displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line

num=1
while [ $num -le 10 ]
do
	echo "Best School"
	if ((num == 9))
	then
		echo "Hi"
	fi

	((num++))
done
